[PHP]
memory_limit=512M
max_execution_time=300
max_input_time=300
upload_max_filesize=50M
post_max_size=50M
max_input_vars=3000
expose_php=Off
display_errors=Off
log_errors=On
error_log=/var/www/html/storage/logs/php_errors.log
